index:
    path: /
    controller: App\Controller\Web\DefaultController::index

contacts:
    path: /contacts
    controller: App\Controller\Web\DefaultController::contacts

show:
    path: /news/{slug}
    controller: App\Controller\Web\ArticleController::show

quotes:
    path: /quotes
    controller: App\Controller\Web\DefaultController::quotes