index:
    path: /
    controller: App\Controller\DefaultController::index

contacts:
    path: /contacts
    controller: App\Controller\DefaultController::contacts

show:
    path: /news/{slug}
    controller: App\Controller\ArticleController::show

showAll:
    path: /showAll
    controller: App\Controller\ProductRepository::showAll

commit:
    path: /infoCommit/{nameAndRepo}
    requirements:
        nameAndRepo: .+
    controller: App\Controller\InfoCommitController::gitCommitsList